name              'proj-seagl'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures proj-seagl'
issues_url        'https://github.com/osuosl-cookbooks/proj-seagl/issues'
source_url        'https://github.com/osuosl-cookbooks/proj-seagl'
chef_version      '>= 16.0'
version           '1.2.1'

depends           'osl-nextcloud'
depends           'sudo'
depends           'users'

supports          'almalinux', '~> 8.0'
