name              'proj-seagl'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures proj-seagl'
issues_url        'https://github.com/osuosl-cookbooks/proj-seagl/issues'
source_url        'https://github.com/osuosl-cookbooks/proj-seagl'
chef_version      '>= 16.0'
version           '0.1.0'

supports          'centos', '~> 7.0'
supports          'centos', '~> 8.0'
