name              'proj-seagl'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures proj-seagl'
issues_url        'https://github.com/osuosl-cookbooks/proj-seagl/issues'
source_url        'https://github.com/osuosl-cookbooks/proj-seagl'
chef_version      '>= 16.0'
version           '1.1.0'

depends           'users'
depends           'sudo'
depends           'osl-mysql'
depends           'osl-nextcloud'

supports          'centos_stream', '~> 8.0'
